### ISSUE TITLE
Runtime error FileNotFoundError: [Errno 2] No such file or directory: '/root/.das/db/main.json'

### ISSUE THREAD

**Issue by neginsadeghi** [snovvcrash/DivideAndScan#4]
I just cloned the repo and run the following commands : 

/tmp/DivideAndScan# alias das='docker run -it --rm --name das -v ~/.das:/root/.das -v `pwd`:/app divideandscan:latest'

/tmp/DivideAndScan# das scan -hosts 185.165.116.100-185.165.116.200 -oA report1

and here is the error that I faced : 

Traceback (most recent call last):
  File "/usr/local/bin/das", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/das/divideandscan.py", line 158, in main
    sr = ScanRun(str(P), args.hosts, args.ports)
  File "/usr/local/lib/python3.9/dist-packages/das/scan.py", line 35, in __init__
    self.db = TinyDB(db_path)
  File "/usr/local/lib/python3.9/dist-packages/tinydb/database.py", line 94, in __init__
    self._storage: Storage = storage(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/tinydb/storages.py", line 102, in __init__
    touch(path, create_dirs=create_dirs)
  File "/usr/local/lib/python3.9/dist-packages/tinydb/storages.py", line 31, in touch
    with open(path, 'a'):
FileNotFoundError: [Errno 2] No such file or directory: '/root/.das/db/main.json'

**Comment by snovvcrash** [comment]
Please, read the [How to Use](https://github.com/snovvcrash/DivideAndScan#how-to-use) section of README. You have to fill the DB with `add` module before proceeding to `scan`.
